### ISSUE TITLE
Not recognising pwsh commands

### ISSUE THREAD

**Issue by brazarb** [aliencube/publish-profile-actions#7]
In my workflow

```
- name: Get publish profile
  id: publishprofile
  uses: aliencube/publish-profile-actions@v1
  env:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  with:
    resourceGroupName: rgName
    appName: appName
```

Not sure if it matters, but I'm using the setup-dotnet action using 6.0.x. The Docker container and the entrypoint.ps1 seem to work locally, just in Github I'm getting this issue.

![image](https://user-images.githubusercontent.com/111027880/201807358-1ed9f8b2-4caa-49a5-9288-e0e11bd27f64.png)
